### ISSUE TITLE
URL is not appearing 

### ISSUE THREAD

**Issue by Nakamcode** [Aadarsh805/100daysofcode-tracker#29]
### URL on Github page is not working

![Screenshot (62)](https://user-images.githubusercontent.com/89482825/215478015-120714bb-2cec-4a79-99cb-e44ab7fccc78.png)

**Comment by Aadarsh805** [comment]
> ### URL on Github page is not working
> ![Screenshot (62)](https://user-images.githubusercontent.com/89482825/215478015-120714bb-2cec-4a79-99cb-e44ab7fccc78.png)

yeah it's because we have not done anything on the home route, it's yet to be built

**Comment by Nakamcode** [comment]
Ok
