### ISSUE TITLE
Add contributions.md,

### ISSUE THREAD

**Issue by ChinmayMhatre** [Aadarsh805/100daysofcode-tracker#75]
These are important for open source contributors

**Comment by the-amazing-atharva** [comment]
Hi!
I would like to add these two files
+ CODE OF CONDUCT
+ LICENSE

**Comment by Aadarsh805** [comment]
> Hi! I would like to add these two files
> 
> * CODE OF CONDUCT
> * LICENSE

cool assigned you @the-amazing-atharva and thank you for your interest in this project
